# VS2017 image uses Windows Server 2016.
image:
#   - Visual Studio 2015
  - Visual Studio 2017
environment:
  matrix:
    - python_version: 2
    - python_version: 3
build: off
test_script:
  - C:\Python37\python -m pip install flake8
  - C:\Python37\python -m flake8 wmidevicemanager
  - C:\Python37\python -m pip install requests
  - C:\Python37\python utils/download_python.py python.exe %python_version%
  - utils\python.exe -c "import sys; print(sys.version)"
  - utils\python.exe -m unittest tests.test_wmidevicemanager
deploy: off
