# VS2017 image uses Windows Server 2016.
image:
#   - Visual Studio 2015
  - Visual Studio 2017
build: off
test_script:
  - C:\Ruby23\bin\ruby.exe python/download_python.rb python.exe 2
  - python\python.exe -c "import sys; print(sys.version)"
  - python\python.exe python/test.py
  - C:\Ruby23\bin\ruby.exe python/download_python.rb python.exe 3
  - python\python.exe -c "import sys; print(sys.version)"
  - python\python.exe python/test.py
deploy: off