# VS2017 image uses Windows Server 2016.
image:
#   - Visual Studio 2015
  - Visual Studio 2017
build: off
test_script:
  - python tests/download_python.py python.exe 2
  - tests\python.exe -c "import sys; print(sys.version)"
  - tests\python.exe -m unittest tests.test_wmidevicemanager
  - python tests/download_python.py python.exe 3
  - tests\python.exe -c "import sys; print(sys.version)"
  - tests\python.exe -m unittest tests.test_wmidevicemanager
deploy: off