
jobs:
- job: windows
  displayName: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: git config --global core.autoCRLF false
    displayName: "Disable git autoCRLF"
  - checkout: self
    displayName: "Checkout"
    fetchDepth: 50
  - script: ruby.exe tests/download_python.rb python.exe 2
    displayName: download python2
  - script: tests\python.exe -c "import sys; print(sys.version)"
    displayName: version
  - script: tests\python.exe python/test_wmidevicemanager.py
    displayName: Test Python2
  - script: ruby.exe tests/download_python.rb python.exe 3
    displayName: download python3
  - script: tests\python.exe -c "import sys; print(sys.version)"
    displayName: version
  - script: tests\python.exe python/test_wmidevicemanager.py
    displayName: Test Python3
